mcanouil/awesome-quarto

README.md
Hi Mickaël,
thanks for your curated list. Happy to contribute! Let me know if I need to change anything,
Best,
Albert
=> Fixed a typo, added my Quarto blog guide and my Quarto styling video

README.md
This PR adds a new arXiv template to the list of available journal templates:
- [arXiv](https://github.com/mikemahoney218/quarto-arxiv) - Template for arXiv-style preprints.
This will likely be of interest for folks generating preprints for non-arXiv repositories, which often require you to upload the PDF directly (rather than arXiv, which has a build service).
```
```
=> Add arXiv template to list of journal templates

README.md
=> Add reveal-auto-agenda

README.md
- style: use proper syntax for reveal.js
=> style: use proper syntax for reveal.js

README.md
- [Program Evaluation for Public Service (course)](https://github.com/andrewheiss/evalf22.classes.andrewheiss.com) - Website for graduate-level course on program evaluation and causal inference using R, built with Quarto.
- [Sketchy HTML](https://github.com/schochastics/quarto-sketchy-html) - A template for quarto to create sketchy looking html documents.
- [Bioconductor Community Blog](https://github.com/Bioconductor/biocblog) - A Quarto Blog for Bioconductor community.
- [YouTube embed](https://github.com/sellorm/quarto-youtube-embed) - This extension provides shortcodes to embed YouTube videos.
- [Welcome to Quarto 2-hour Workshop](https://www.youtube.com/watch?v=yvi5uXQMvu4) - Getting Started with Quarto in a 2-hour workshop led by Tom Mock, RStudio (slides: …
=> Next Release

README.md, fake.md
Rearrange items in the categories to make it more clear.
=> Rearrange items anf fix linter issues

README.md
- [iconify](https://github.com/mcanouil/quarto-iconify) - This extension provides shortcodes to [Iconify](https://icon-sets.iconify.design/) icons library (*HTML-based format only*).  
Fixes #34 
- [twitter](https://github.com/sellorm/quarto-twitter-embed) - This extension provides shortcodes to embed tweets in HTM-based documents.  
Fixes #33
- [social-share](https://github.com/schochastics/quarto-social-share) - This extension allows to add buttons to share HTM-based documents on various social media platforms.  
Fixes #35
- [Interactive Molecular Content](https://www.valencekjell.com/posts/2022-08-13-interactive/) - A blog post showing how to embed interactive content (_i.e._, molecular visualisation) in webpages with Quarto using Bokeh, 3DMol.js and NGL.  
Fixes #38
- …
=> New-release

README.md
- [nutshell](https://github.com/schochastics/quarto-nutshell) - This extension provides a filter to embed [Nutshell](https://github.com/ncase/nutshell) in HTM-based documents.  
Fixes #42
```
```
=> feat: add nutshell extension

README.md
- [J.J. Allaire (\@jjallaire)](https://github.com/jjallaire/) - Member of Quarto core team (twitter: [\@fly_upside_down](https://twitter.com/fly_upside_down)).
- [Christophe Dervieux (\@cderv)](https://github.com/cderv) - Member of Quarto core team (twitter: [\@chrisderv](https://twitter.com/chrisderv)).
- [Carlos Scheidegger (\@cscheid)](https://github.com/cscheid) - Member of Quarto core team (twitter: [\@scheidegger](https://twitter.com/scheidegger)).
- [Charles Teague (\@dragonstyle)](https://github.com/dragonstyle) - Member of Quarto core team (twitter: [\@dragonstyle](https://twitter.com/dragonstyle)).
- [Yihui Xie (\@yihui)](https://github.com/yihui) - Member of Quarto core team (twitter: [\@xieyihui](https://twitter.com/xieyihui)).
- [Tom Mock …
=> feat: add twitter accounts

README.md
added ds-econ post to the collection (the one you retweeted to save it)
New post under chapter blog post: "Heads up! Quarto is here to stay."
```
```
=> Blog: Heads up! Quarto is here to stay. 

README.md
- [letter](https://github.com/mcanouil/quarto-letter) - A template for Quarto to create letter PDF documents.
```
```
=> fix: add letter format

README.md
- [section-bibliographies](https://github.com/pandoc-ext/section-bibliographies) - This extension provides a filter to create a separate bibliography for each section or chapter.  
Fixes #52
```
```
=> fix: section-bibliographies

README.md
- [video](https://github.com/allenmanning/video) - This extension provides shortcodes to embed videos in HTML-based documents.
Fixes #55
```
```
=> fix: Video shortcode

README.md
- [RStudio & VSCode snippets](https://gist.github.com/jthomasmock/11acebd4448f171f786e01397df34116) - RStudio & VSCode snippets to ease typesetting with Quarto.  
Fixes #56
```
```
=> fix: Snippets for VSCode and RStudio

README.md
- [Quarto Website with GitHub Actions](https://tarleb.com/posts/quarto-with-gh-pages/) - Publih a Quarto website automatically every time it is updated via GitHub Actions.  
Fixes #53
```
```
=> fix: Quarto Website with GitHub Actions

README.md
- [Quarto for the Curious](https://www.rstudio.com/conference/2022/talks/quarto-for-rmarkdown-users/) - A Quarto overview given at RStudio::conf(2022) (materials: <https://thomasmock.quarto.pub/quarto-curious/>).  
Fixes #58
- [Hello Quarto: Share • Collaborate • Teach • Reimagine](https://www.rstudio.com/conference/2022/keynotes/collaborate-with-quarto/) - Keynote by Mine Çetinkaya-Rundel & Julia Stewart Lowndes highlighting how they leverage Quarto in open-science at RStudio::conf(2022) (materials: <https://github.com/mine-cetinkaya-rundel/hello-quarto>).  
Fixes #60
- [Websites & Books & Blogs, oh my! Creating Rich Content with Quarto](https://www.rstudio.com/conference/2022/talks/sessions/quarto-deep-dive/websites-books-blogs-quarto/) - Talk by Devin Pastoor at RStudio::conf(2022) …
=> RStudio::conf(2022)

README.md
- [Slidecraft 101: Colors and Fonts](https://www.emilhvitfeldt.com/post/slidecraft-colors-fonts/) - A blog post about "The art of putting together slides that are functional and aesthetically pleasing" using Quarto presentation format by Emil Hvitfeldt.  
Fixes #70
```
```
=> fix: Slidecraft 101: Colors and Fonts

.github/workflows/tweet-release.yml
=> ci: add tweet on release

README.md
- fix: video was transferred to quarto-ext
=> fix: video was transferred to quarto-ext

README.md
- [hikmah](https://github.com/andrewheiss/hikmah-academic-quarto) - An opinionated template for Quarto to create PDF documents with support to `biblatex-chicago` and more.  
Fixes #80
```
```
=> fix: Add new PDF template example

.github/workflows/tweet-item.yml
=> ci: tweet random item GHA

.github/workflows/tweet-item.yml, README.md
fix: hard wrapping for some items
=> Fix hard wrapping

.github/workflows/tweet-item.yml, .github/workflows/tweet-release.yml
- fix: rm affectation sign.
- fix: remove escaping for twitter username in tweet.
- feat: tweet the new addition in thread.
=> ci: tweet new additions in release thread

.github/workflows/tweet-item.yml
ci: exclude quarto-journals and set seed
=> ci: exclude quarto-journals and set seed

.github/workflows/tweet-item.yml
ci: fix quarto-journals kept and not excluded
=> ci: fix quarto-journals kept and not excluded

.github/workflows/tweet-item.yml, .github/workflows/tweet-release.yml
- ci: add robot icon to show ci tweets
=> ci: add robot icon to show ci tweets

.github/workflows/tweet-item.yml, .github/workflows/tweet-release.yml
ci: rm hashtags to shorten tweet (mostly)
=> ci: rm hashtags to shorten tweet (mostly)

README.md
- add quarto-qrcode shortcode extension.
Fixes #92 
```
```
=> feat: add quarto-qrcode shortcode extension

README.md
- feat: SportRxiv Article Template  
Fixes #90
```
```
=> feat: SportRxiv Article Template

README.md
- feat: Reveal.js Nes template  
Fixes #89
```
```
=> feat: Reveal.js Nes template

README.md
- feat: RStudio Meetup  
Fixes #88
```
```
=> feat: RStudio Meetup

README.md
- feat: Python for Data Analysis, 3E
Fixes #85
```
```
=> feat: Python for Data Analysis, 3E

.github/workflows/tweet-item.yml
- fix: Tweak tweet post content to avoid over 280 char.  
Fixes #103
=> fix: tweak tweet post content to avoid over 280 char

README.md
- [animate](https://github.com/mcanouil/quarto-animate) - This extension provides support and shortcode to [animate.css](https://animate.style/) (*HTML-based format only*).  
Fixes #101
```
```
=> fix: issue #101

README.md
- [titlepage](https://github.com/nmfs-opensci/quarto_titlepages) - This extension template brings several title pages for your PDF documents from one yaml option. 
Fixes #37
```
```
=> fix: Custom title page for LaTeX documents/books

README.md
- [inrae](https://github.com/davidcarayon/quarto-inrae-extension) - [INRAE](https://www.inrae.fr/) extension template with several formats (HTML and PDF-based). 
Fixes #104
```
```
=> fix: Quarto templates for INRAE

README.md
- [Scrivener](https://forum.literatureandlatte.com/t/scrivener-quarto-a-technical-academic-publishing-workflow/129769) - Quarto support to [Scrivener](https://www.literatureandlatte.com/) via Scrivener Template.  
Fixes #102
```
```
=> fix: Add Scrivener to supported editors

README.md
- [roughnotation](https://github.com/EmilHvitfeldt/quarto-roughnotation) - An extension that uses the [roughnotation](https://roughnotation.com/) JavaScript library to add animated annotations to `revealjs` documents.  
Fixes #113
```
```
=> fix: roughnotation extension

README.md
- [code-visibility](https://github.com/jjallaire/code-visibility) - This extension implements some directives for filtering code and stream output included within a document.  
Fixes #115
```
```
=> fix: "code-visibility" extension

README.md
- [elevator](https://github.com/mcanouil/quarto-elevator) - This extension provides support and shortcode to Elevator.js.  
Fixes #114
```
```
=> fix: Elevator.js extension

README.md
Adds a link to a Quarto workshop on the [RSECon'22](https://rsecon2022.society-rse.org/)
Links:
- Slides: https://warwickcim.github.io/quarto-workshop/slides/slides.html#/title-slide
- Repo with use cases and discussion: https://github.com/WarwickCIM/quarto-workshop
```
```
=> Add link to RSE Con 22 workshop

README.md
- [Quarto Devcontainer Feature](https://github.com/rocker-org/devcontainer-features/tree/main/src/quarto-cli) - Add Quarto CLI to your [Development Containers](https://containers.dev/) as a feature.  
Fixes #124
```
```
=> fix: Quarto CLI Devcontainer Feature (#124)

README.md
- [AffCom Lab Website](https://github.com/jmgirard/affcomlab) - A research lab Quarto Blog/website using custom listing pages for people and publications.  
Fixes #127
```
```
=> fix: Research lab website example

README.md
- [Making Slides in Quarto with Reveal.js](https://meghan.rbind.io/blog/quarto-slides/) - A blog post about making slides in Quarto with Reveal.js and how to use emojis or customise the slides by Meghan Hall.  
Fixes #126
```
```
=> fix: Making Slides in Quarto with reveal.js (#126)

README.md
- [Beautiful Reports and Presentations with Quarto](https://www.youtube.com/watch?v=hbf7Ai3jnxY) - RStudio Meetup: Beautiful Reports and Presentations with Quarto by Tom Mock (materials: <https://github.com/jthomasmock/quarto-reporting>).  
Fixes #125
```
```
=> fix: Beautiful reports and presentations with Quarto | Led by Tom Mock, RStudio (#125)

README.md
=> fix: Cleanup Quarto extensions

README.md
- [Tutorial: Creating your personal website using Quarto](https://ucsb-meds.github.io/creating-quarto-websites/) - A step-by-step guide for setting up a personal website using Quarto by Samantha Csik.  
Fixes #133
```
```
=> fix: Creating your personal website using Quarto

README.md
- [A beginner's guide to using Observable JavaScript, R, and Python with Quarto](https://www.infoworld.com/article/3674789/a-beginners-guide-to-using-observable-javascript-r-and-python-with-quarto.html) - This article shows you how to set up a Quarto document to use Observable JavaScript, including how to pass data from R or Python to an Observable code chunk.  
Fixes #134
```
```
=> Fix-issue134

README.md
- [shinylive](https://github.com/quarto-ext/shinylive) - This extension lets you embed [Shinylive](https://shiny.rstudio.com/py/docs/shinylive.html) ([Shiny for Python](https://shiny.rstudio.com/py/)) applications in a Quarto document.  
Fixes #139
```
```
=> fix: Qhinylive Quarto extension

README.md
- [social-embeds](https://github.com/sellorm/quarto-social-embeds) - A Quarto extension that provides shortcodes to embed content from across the web into HTML-based documents.  
Fixes #142
```
```
=> fix: Social embeds extension

README.md
- [Tutorial: Customizing Quarto Websites - Make your website stand out using SASS & CSS](https://ucsb-meds.github.io/customizing-quarto-websites/) - Slides by Samantha Csik about using SASS and CSS to customise HTM Quarto website (materials: <https://github.com/UCSB-MEDS/customizing-quarto-websites>)  
Fixes #137
```
```
=> fix: Customising Quarto Website

README.md
- [matrix BOT](https://github.com/rgomez90/matrix-bot) - A little bot for the [matrix-network](https://matrix.org/) that listens for some Quarto files and returns the PDF into the matrix channel.  
Fixes #138
```
```
=> fix: a simple matrix-quarto-bot for pdf-files

README.md
- [Six Productivity Hacks for Quarto](https://www.rstudio.com/blog/6-productivity-hacks-for-quarto/) - A blog post showing six tips from the re-use content across documents, the insertion of Pandoc divs and spans to continuous deployment with GitHub Actions.  
Fixes #153
```
```
=> fix: 6 Productivity Hacks for Quarto

README.md
- [Let’s make maps with `bertin.js` in Quarto](https://neocarto.github.io/bertin/examples/quarto.html) - A HTML document showing how to draw maps with bertin.js in Quarto.  
Fixes #154
```
```
=> fix: Bertin.js and Quarto to draw maps

README.md
- [Computo](https://github.com/computorg/computo-quarto-extension) - Template for *Computo* journal.  
Fixes #156
```
```
=> fix: Computo Quarto extension

.github/ISSUE_TEMPLATE/suggestion.yml, README.md
- [NOAA Quarto Simple Website](https://github.com/nmfs-opensci/NOAA-quarto-simple) - NOAA simple is a repository template for a simple Quarto website that looks like a "book".  
Fixes #157
```
```
=> fix: NOAA simple Quarto format

README.md
- [simple-article](https://github.com/cmarquardt/quarto-simple-article) - This is a Quarto template that assists you in creating a simple, journal article-like document.
Fixes #159
```
```
=> fix: Simple Article Template for Quarto

README.md
- [bsicons](https://github.com/shafayetShafee/bsicons) - This extension provides shortcodes to [Bootstrap](https://icons.getbootstrap.com/) icons library (*HTML-based format only*).  
Fixes #168
```
```
=> fix: Bootstrap icons shortcode

README.md
- [collapse-callout](https://github.com/shafayetShafee/collapse-callout) - A filter that provides global options to make the [Callout Blocks](https://quarto.org/docs/authoring/callouts.html) collapsible (*HTML-based format only*).  
Fixes #168
```
```
=> fix: quarto-gouv Quarto template

README.md
- [How to add some personality to your Quarto Blog](https://www.ddanieltan.com/posts/blogtips/) - A blog post sharing some of the added features and tweaks users can make on top of the standard blog templates to inject some personality into their blog.  
Fixes #162
```
```
=> fix: Tips to add some personality to your Quarto Blog

README.md
=> Add quartaki workshop

README.md
- [include-code-files](https://github.com/SamEdwardes/include-code-files) - Include code from files using code cells option/attribute.
Fixes #186
```
```
=> fix: include-code-files Extension For Quarto

README.md
- [designmode](https://github.com/EmilHvitfeldt/quarto-designmode) - A quarto extension, adding a toggle for [designMode](https://developer.mozilla.org/en-US/docs/Web/API/Document/designMode) in `html` and `revealjs` formats.  
Fixes #187
```
```
=> fix: designMode Quarto extension

README.md
- [metropolis-theme](https://codeberg.org/pat-s/quarto-metropolis) - Opinionated port of the Metropolis template for Quarto `revealjs` presentation.
Fixes #189
```
```
=> fix: Metropolis Quarto template

README.md
- [Quarto: Create Beautiful Documents with R, Python, Julia and Observable (Runapp 2022 talk)](https://github.com/jimjam-slam/talk-runapp-quarto-2022) - See clides [here](https://runapp2022.talks.jamesgoldie.dev/).  
Fixes #184
```
```
=> fix: Quarto + OJS 🤯

README.md
- [Use R to Generate a Quarto Blogpost](https://themockup.blog/posts/2022-11-08-use-r-to-generate-a-quarto-blogpost/) - A blog post about using R to generate Quarto blog post by Tom Mock.  
Fixes #185
```
```
=> fix: Use R to generate a Quarto blogpost

README.md
- [Introduction to Quarto](https://www.youtube.com/watch?v=y6_xMIBKuP4) - R-Ladies St. Louis: Introduction to Quarto by Isabella Velásquez (materials: <https://github.com/ivelasq/2022-10-27_intro-to-quarto>).  
Fixes #189
```
```
=> fix: R-Ladies STL: Introduction to Quarto with Isabella Velásquez

README.md
- [Introduction to Quarto](https://www.youtube.com/watch?v=y6_xMIBKuP4) - A blog post about opinionated best practices for Quarto documents.  
Fixes #190
```
```
=> fix: Best practices for Quarto documents (opinionated blog post)

README.md
- [Quarto YouTube Playlist](https://www.youtube.com/playlist?list=PLDqZV53PcnYxnBYuEdSBxnOwdKLGaoKGg) - A YouTube playlist of videos about Quarto and Pandoc by Eli Holmes.  
Fixes #190
```
```
=> fix: Quarto YouTube playlist

README.md
=> fix: Add Quarto team Mastodon handles

README.md
=> chore: draft release

README.md
- Adds a Quarto journal template for ASM mSystems.
```
```
=> feat: add journal template for ASM mSystems

README.md
Add quarto-confetti as a new extension
https://github.com/ArthurData/quarto-confetti
```
```
=> docs: Suggest quarto-confetti extension

README.md
- [Quantum Jitter](https://github.com/cgoo4/quantumjitter) - A Quarto website / blog with a custom theme (adapted from flatly / darkly), day / night landing page and a novel 404 page.
Fixes #206
```
```
=> fix: Quantum Jitter website

README.md
- [code-insertion](https://github.com/feynlee/code-insertion) - This extension enables code insertion immediately before and/or after a post/page for website and blog projects.
Fixes #207
```
```
=> fix: code-insertion Quarto extension

README.md
- [snow](https://github.com/EmilHvitfeldt/quarto-snow) - This extension adds falling snowflakes in `html` and `revealjs` formats.
Fixes #212
```
```
=> fix: Snow extension for Quarto

README.md
- [Iframes Gallery](https://github.com/EmilHvitfeldt/quarto-iframe-examples) - A gallery of iframes that could be used in Quarto `revealjs` format.
Fixes #213
```
```
=> fix: Quarto Revealjs iframes examples

README.md
- [Andrew Heiss's website](https://github.com/andrewheiss/ath-quarto) - Andrew Heiss's website with custom EJS format, footer, 404 page, (S)CSS, and many more customisations.
Fixes #208
```
```
co-authored-by: Andrew Heiss <andrewheiss@users.noreply.github.com>
=> fix: Andrew Heiss  Website

README.md
- [Ella Kaye's website](https://github.com/EllaKaye/ellakaye.co.uk) - Ella Kaye's website with Boostrap Grid card home page layout, CSS animatation in navigation bar, and light/dark mode.
Fixes #211
```
```
co-authored-by: Ella Kaye <EllaKaye@users.noreply.github.com>
=> fix: Ella Kaye website

README.md
Add a new quarto extension.
```
```
- [x ] Be sure to have read the [contributing guidelines](CONTRIBUTING.md).
=> Add swissbiopics

README.md
- [tufte](https://github.com/fredguth/tufte-quarto) - A Quarto extension template for Tufte-style book (`html` and `pdf`).  
Fixes #163
co-authored-by: Fred Guth <fredguth@users.noreply.github.com>
```
```
=> fix: Tufte book layout for Quarto

README.md
- [RStudio](https://posit.co/products/open-source/rstudio/) - RStudio IDE by [Posit PBC](https://posit.co/) natively supports Quarto.  
Fixes #222
co-authored-by: <@users.noreply.github.com>
```
```
=> fix: RStudio IDE

README.md
- [chord-sheet](https://github.com/dfalbel/chord-sheet) - This extension provides support for rendering chord sheets in `html` and `revealjs` formats.  
Fixes #226
- [inadsense](https://github.com/jskherman/inadsense) - This extension provides shortcode for inserting Google Adsense ads in `html` and `revealjs` formats.  
Fixes #228
- [asce](https://github.com/juliantao/quarto-asce) - Template for *American Society of Civil Engineers* journals and conference proceedings.  
Fixes #229
- [qletter](https://github.com/juliantao/qletter) - An opinionated template to create letter PDF documents.  
Fixes #230
- [nastatement](https://github.com/nareal/nastatement) - A template for creating a statement PDF letter.  
Fixes #231
- [naletter](https://github.com/nareal/naletter) - An opinionated …
=> fix: add multiple extensions

README.md
- [Workshop: Mi primer blog con Quarto](https://perezp44.github.io/taller.primer.blog/) - A workshop in Spanish by Pedro J. Pérez to create a blog with Quarto (materials: <https://github.com/perezp44/taller.primer.blog>).  
Fixes #223
co-authored-by: Pedro J. Pérez <perezp44@users.noreply.github.com>
```
```
=> fix: Mi primer blog con Quarto

README.md
- [Adding Subscriptions to a Quarto Site](https://forbo7.github.io/forblog/posts/7_blog_subscriptions.html) - A blog post about how to add a subscription form to your Quarto blog.  
Fixes #239
co-authored-by: Salman Naqvi <ForBo7@users.noreply.github.com>
```
```
=> fix: Adding Subscriptions to a Quarto Site

README.md
- [I'm an R user: Quarto or R Markdown?](https://www.jumpingrivers.com/blog/quarto-rmarkdown-comparison/) - A blog post comparing Quarto and R Markdown from an R user perspective by [Jumping Rivers](https://www.jumpingrivers.com/).  
Fixes #239
```
```
=> fix: Quarto & RMarkdown blog post

README.md
- [lcars](https://github.com/mccarthy-m-g/quarto-lcars-theme) - An LCARS template for Quarto `html` documents.  
Fixes #257
co-authored-by: Michael McCarthy <mccarthy-m-g@users.noreply.github.com>
=> fix: LCARS Quarto HTML template

README.md
- [iop](https://github.com/sebdunnett/quarto-iop) - Template for *Institute of Physics* journal.  
Fixes #259
co-authored-by: Sebastian Dunnett <sebdunnett@users.noreply.github.com>
=> fix: Institute of Physics (IOP) Quarto Journal template

README.md
- [Create your Data Science Portfolio with Quarto](https://www.youtube.com/watch?v=xtSFXtDf4cM) - In this video by Deepsha Menghani, learn how you can easily create a Data Science Portfolio website and deploy it instantly with the help of Quarto (materials: <https://deepshamenghani.quarto.pub/portfolio-with-quarto-workshop/#/title-slide>).   
Fixes #260
co-authored-by: deepshamenghani <deepshamenghani@users.noreply.github.com>
=> fix: Create your Data Science Portfolio with Quarto

README.md
Adds the kakashi reveal.js theme 
```
```
=> add kakashi theme

README.md
=> added four extensions

README.md
This PR adds my own [quarto-brief](https://github.com/mavam/quarto-brief) template for writing DIN 5008 compliant German letters using KOMA-script.
```
```
=> Add quarto-brief

README.md
Fixes #282
co-authored-by: Andrés Cruz <arcruz0@users.noreply.github.com>
=> fix: compact-pdf Quarto Format

README.md
Add Quarto for Python user blog post by Jumping Rivers.
=> feat: add quarto for user blog post

README.md
This PR fixes grammer/typos raised in https://github.com/sindresorhus/awesome/pull/2550#issuecomment-1480877823
=> fix: grammar/typos

README.md
=> add "A Coffee with Quarto and Neovim on YT"

README.md
=> fix: Update: 360-info/sverto → jimjam-slam/sverto

README.md
Fixes #292
co-authored-by: James J Balamuta <coatless@users.noreply.github.com>
=> fix: Quarto webR

README.md
Fixes #294
co-authored-by: Jon Cardoso-Silva<jonjoncardoso@users.noreply.github.com>
=> fix: Quarto-based template for uni course websites

README.md
Fixes #303
co-authored-by: Michael Schramm <mps9506@users.noreply.github.com>
=> fix: quarto-cv

README.md
Fixes #307
co-authored-by: Ute Hahn <ute@users.noreply.github.com>
=> fix: Custom numbered blocks

README.md
Fixes #308
co-authored-by: Shafayet Khan Shafee <shafayetShafee@users.noreply.github.com>
=> fix: A Quarto filter to run sql queries interactively in html documents

README.md
- Fixes #320
co-authored-by: eitsupi <eitsupi@users.noreply.github.com>
- Fixes #322
co-authored-by: Nicola Rennie <nrennie@users.noreply.github.com>
- Fixes #326
co-authored-by: 
Brian Tarran <brtarran@users.noreply.github.com>
=> feat: new release

README.md
Fixes #328
co-authored-by: Bruno Rodrigues <b-rodrigues@users.noreply.github.com>
=> fix: A blog post about using Quarto to self-publish a book on Leanpub and Amazon

README.md
Fixes #329
co-authored-by: Shandiya (SUN-dia) Balasubramaniam <shandiya@users.noreply.github.com>
=> fix: Quarto slides from Victorian Biodiversity Conference 2023

README.md
Fixes #332
co-authored-by: Christopher Kenny <christopherkenny@users.noreply.github.com>
=> fix: Creating Quarto Journal Article Templates

README.md
Fixes #333
co-authored-by: Aditya (Arie) Wijaya <ariewjy@users.noreply.github.com>
=> fix: Python-based tutorial in Making Quarto Website

README.md
Fixes #334
co-authored-by: Enrico Spinielli <espinielli@users.noreply.github.com>
=> fix: new journal template: JOAS

README.md
Adds:
- A blog post containing notes on porting a Hugo Apéro blogdown site to Quarto. Useful in providing stepping stones to anyone with a blogdown site who is considering making the switch to Quarto: https://silviacanelon.com/blog/2023-09-29-hello-quarto
- A website styled to resemble the Hugo Apéro theme. Useful to anyone who likes the Hugo Apéro website theme and would like to adopt the style: https://silviacanelon.com
```
```
=> feat: new blog post and website example

README.md
=> fix: "quakr" Reveal.js template

README.md
=> fix: Suggestion: Quarto website tutorial and template

README.md
Resolves #348, resolves #349, resolves #351, resolves #356, resolves #358
=> feat: several new entries

README.md
- *__Tutorials & workshops__*
- [Tutorial: Create Your Website with Quarto](https://www.marvinschmitt.com/blog/website-tutorial-quarto/) - A tutorial on how to create a website using Quarto by Marvin Schmitt.
- [Tutorial: Publish a Quarto website with Netlify](https://jadeyryan.com/blog/publish-quarto-website/) - A comprehensive blog post walking through how to create a Quarto website, connect it to GitHub, deploy & publish it with Netlify by Jadey Ryan.
- *__Blog posts__*
- [Hello Quarto: Porting my Website from Hugo Apéro](https://silviacanelon.com/blog/2023-09-29-hello-quarto/) - A blog post detailing a user's experience of porting a blogdown Hugo Apéro site to Quarto, with content including design ideas, CSS tips, HTML partials, setting up redirects, and others.
- *__Talks and …
=> chore: prepare new release

README.md
Adds slides from my posit::conf(2023) talk about parameterized Quarto reports. 
This talk gives an overview to parameterized reporting with Quarto and provides a real-world use case of using parameters to generate many reports from the same `qmd` file. I discuss parameterized reporting 101, preparing data to be used in parameterized reports, and creating content that is both consumable and accessible to all audiences.
https://jadeynryan.github.io/2023_posit-parameterized-quarto/
```
- [item name](https link) - Description …
```
=> feat: parameterized quarto talk

README.md
=> feat: add 6-minutes video for publishing with GitHub

README.md
Adds an entry for a multi-lingual quarto website for a scientific research project: [https://nascent-peru.github.io/](https://nascent-peru.github.io/) 
```
```
=> feat: new website example

README.md
Include Marten Walk's academic website, which features a custom theme inspired by the Financial Times, offering a modern look and numerous customizations such as custom fonts and graphs.
Fixes #383
=> chore: Add Marten Walk's website to real life examples

README.md
Include a YouTube playlist of short video tutorials aimed at complete novices to help newcomers learn to work with the Quarto Visual Editor and RStudio.
Fixes #387.
=> feat: Add video tutorials for Quarto beginners

README.md
Include Positron in the list of supported IDEs in the README file.
=> feat: Add Positron as a supported IDE

README.md
=> feat: quarto amsmath

README.md
=> feat: add altdoc

README.md
=> feat: add skimpy documentation example

README.md
=> feat: add blog post on reveal.js

README.md
=> feat: Add blog post on using the embed shortcode for multi-engine Quarto documents

README.md
=> feat: add migration guide from Wowchemy to Quarto

README.md
=> feat: Add Slidecrafting book reference to README
