- README.md
fix: abstract-section extension moved to pandoc-ext org
> fix: abstract-section extension moved to pandoc-ext org

- .github/workflows/tweet-item.yml
- README.md
ci: rm html comments from tweet.
fix: use 'revealjs' as defined in Quarto instead of 'reveal.js'.
> ci: rm html comments from tweet

- README.md
- [animate](https://github.com/mcanouil/quarto-animate) - This extension provides support and shortcode to [animate.css](https://animate.style/) (*HTML-based format only*).
- [titlepage](https://github.com/nmfs-opensci/quarto_titlepages) - This extension template brings several title pages for your PDF documents from one yaml option.
- [inrae](https://github.com/davidcarayon/quarto-inrae-extension) - [INRAE](https://www.inrae.fr/) extension template with several formats (HTML and PDF-based).
> chore: set featured items

- README.md
- [attribution](https://github.com/quarto-ext/attribution) - A Quarto extension that brings Reveal.js plugin for displaying attribution text sideways along the right edge of the viewport.  
Fixes #135
```
```
> fix: Quarto Extension Attribution

- README.md
- [pointer](https://github.com/quarto-ext/pointer) - A Quarto extension that brings a very simple Reveal.js plugin that adds support for switching the cursor to a 'pointer' style element while presenting.  
Fixes #141
```
```
> fix: Pointer Quarto extension

- README.md
- *__Extensions__*
- [confetti](https://github.com/ArthurData/quarto-confetti) - This extension uses [canvas-confetti](https://github.com/catdad/canvas-confetti) a JavaScript library to send some confetti in your `revealjs` presentation.
- [code-insertion](https://github.com/feynlee/code-insertion) - This extension enables code insertion immediately before and/or after a post/page for website and blog projects.
- [snow](https://github.com/EmilHvitfeldt/quarto-snow) - This extension adds falling snowflakes in `html` and `revealjs` formats.
- *__Templates__*
- [asm](https://github.com/kelly-sovacool/asm-msystems) - Template for the *American Society for Microbiology*, based on the *mSystems* LaTeX template.
- *__Real Life Examples__*
- [Quantum …
> chore: add featured items

- README.md
- [quarto-revealjs-inverse](https://github.com/EmilHvitfeldt/quarto-revealjs-inverse) - The goal of this repository is to provide an example of how to create a inverse class to use in `revealjs` slides.  
Fixes #253
co-authored-by: Emil Hvitfeldt <EmilHvitfeldt@users.noreply.github.com>
> fix: Inverse template Reveal.js for Quarto

- README.md
- [stata-facade](https://github.com/CenterOnBudget/quarto-stata-facade) - A Quarto extension that hides the evidence of faking Stata dynamic content with Python code blocks and [Stata cell magic](https://www.stata.com/python/pystata/notebook/Magic%20Commands1.html).  
Fixes #227
co-authored-by: cz <c-zippel@users.noreply.github.com>
> fix: stata-facade Quarto extension

- README.md
- [quarto-revealjs-seasons](https://github.com/EmilHvitfeldt/quarto-revealjs-seasons) - The is an example of how to create a `revealjs` theme with multiple styles.  
Fixes #254
co-authored-by: Emil Hvitfeldt <EmilHvitfeldt@users.noreply.github.com>
> fix: 'seasons' Quarto Reveal.js template

- README.md
- [authors-block](https://github.com/kapsner/authors-block) - This extension brings the capability to add an author-related header block when rendering `docx` documents with Quarto.  
Fixes #255
co-authored-by: kapsner <kapsner@users.noreply.github.com>
co-authored-by: Christophe Dervieux <cderv@users.noreply.github.com>
> fix: Extensions about author block

- README.md
- [line-highlight](https://github.com/shafayetShafee/line-highlight) - Quarto Extension to implement source code line highlighting and output line highlighting for `html` documents.  
Fixes #256
co-authored-by: Shafayet khan Shafee <shafayetShafee@users.noreply.github.com>
> fix: Extensions about line highlighting the source code and code output for HTML format

- README.md
- [hedgedoc-slides](https://github.com/sokotim/hedgedoc-slides) - A LUA filter to convert `revealjs` presentations to [HedgeDoc](https://hedgedoc.org/) presentations.  
Fixes #258
co-authored-by: Tim Sokollek <sokotim@users.noreply.github.com>
> fix: hedgedoc-slides Quarto filter extension

- README.md
- [Sverto](https://360-info.github.io/sverto/) - Sverto is an extension for Quarto that lets you seamlessly write and include [Svelte](https://svelte.dev/) components, like charts and other visuals, in your Quarto website.  
Fixes #261
co-authored-by: James Goldie <jimjam-slam@users.noreply.github.com>
> fix: Sverto: reactive Svelte components in Quarto

- README.md
- [collapse-social-embeds](https://github.com/shafayetShafee/collapse-social-embeds) - Quarto extension to provide collapsible option to [social-embeds](https://github.com/sellorm/quarto-social-embeds) extension.  
Fixes #263
- [reveal-header](https://github.com/shafayetShafee/reveal-header) - A Quarto extension to add a header to `revealjs` slides as the footer.  
Fixes #264
- [downloadthis](https://github.com/shafayetShafee/downloadthis) - This extension shortcode provides support for adding download buttons to download image/pdf/txt/csv files.  
Fixes #265
co-authored-by: Shafayet khan Shafee <shafayetShafee@users.noreply.github.com>
> fix: Extension about Collapsible Callouts with embedded social content

- README.md
Add bookup custom HTML format.
This PR adds a new HTML custom format called bookup.
```
```
> Add bookup custom HTML format

- README.md
Adds a link to a new "clean" Quarto revealjs theme.
Repo: https://github.com/grantmcdermott/quarto-revealjs-clean
```
```
> Add revealjs ‘clean’ theme

- README.md
Fixes #295
co-authored-by: Shafayet Khan Shafee <shafayetShafee@users.noreply.github.com>
> fix: A Quarto filter to format the python codes using black code formatter

- README.md
This PR adds two blog posts:
- [How to publish your Quarto document/book/website as a Docker container?](https://mickael.canouil.fr/posts/2023-05-07-quarto-docker/) - A blog post describing how to publish your Quarto document/book/website as a Docker container by Mickaël Canouil.
- [How to have images for both light and dark theme?](https://mickael.canouil.fr/posts/2023-05-30-quarto-light-dark/) - A blog post describing how to have images for both light and dark theme by Mickaël Canouil.
> feat: add blog posts on Docker and light/dark images

- README.md
- [version-badge](https://github.com/mcanouil/quarto-version-badge) - An extension for Quarto to provide a shortcode to display software version.
- [preview-colour](https://github.com/mcanouil/quarto-preview-colour) - An extension to add preview colour as a coloured symbol next to colour code.
- [lua-env](https://github.com/mcanouil/quarto-lua-env) - An extension for Quarto to provide access to LUA objects as metadata.
- [spotlight](https://github.com/mcanouil/quarto-spotlight) - An extension for Reveal.js allowing to highlight the current mouse position with a spotlight.
- [cinco-de-mayo](https://github.com/EmilHvitfeldt/quarto-revealjs-cinco-de-mayo) - Cinco de Mayo Quarto `Reveal.js` theme.
- [PNAS](https://github.com/christopherkenny/pnas) - Quarto template for *PNAS*.
- …
> feat: add extensions

- README.md
Adds a ref to the `glossary` extension, a lightweight implementation that copies blocks of content from across many docs and adds them to a different doc as a glossary.
- [glossary](https://github.com/andrewpbray/glossary) - Collect blocks of content across many documents and write them into a glossary.
```
```
> Add glossary extension

- README.md
> fix: "quartodoc": Generate API documentation with Quarto

- README.md
Adds the rainbowR website to the list of awesome websites (as per @mcanouil's suggestion in https://github.com/quarto-dev/quarto-cli/discussions/11651)
- The description starts with an uppercase character and ends with a period. ***Exception requested: "rainbowR" starts with a small 'r' - that is the community name/spelling - so the description starts as such as well***.
```
```
> add rainbowR website

- README.md
This PR makes several minor copy edits to improve consistency and readability:
- Fixes typo "HTM" to "HTML"
- Corrects package name from "ml3r" to "mlr3"
- Fixes miscellaneous spacing and quotation mark issues
- Corrects spelling of "colorblindness"
No content changes or substantive edits were made - these are purely copy edits for consistency and correctness.
> Fix typos and standardize spelling throughout README

- README.md
Add two VSCode extensions: Quarto Wizard and Quarto Wingman.
Enhance the README by adding new sections for R, Julia, Python, Editors, and Miscellaneous, while cleaning up existing entries for clarity and accuracy.
> feat: add two VSCode extensions and clean up list
